version: 0.2

env:
  secrets-manager:
    OWNER: $SECRET_ARN:OWNER
    AWS_REGION: $SECRET_ARN:AWS_REGION
    PROJECT_NAME: $SECRET_ARN:PROJECT_NAME
    API_PORT: $SECRET_ARN:API_PORT
    DB_DATABASE: $SECRET_ARN:DB_DATABASE
    DB_HOST: $SECRET_ARN:DB_HOST
    DB_PASSWORD: $SECRET_ARN:DB_PASSWORD
    DB_PORT: $SECRET_ARN:DB_PORT
    DB_USER: $SECRET_ARN:DB_USER
    BUCKET_NAME: $SECRET_ARN:BUCKET_NAME
    USER_ACCESS_ID: $SECRET_ARN:USER_ACCESS_ID
    USER_ACCESS_SECRET: $SECRET_ARN:USER_ACCESS_SECRET
    SQL_DATABASE_CONNECTION: $SECRET_ARN:SQL_DATABASE_CONNECTION
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $OWNER.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Setting variables dockerfile...
      - sed -i "s/#SQL_DATABASE_CONNECTION#/$SQL_DATABASE_CONNECTION/g" Source/postcard/appsettings.json
      - sed -i "s/#BUCKET_NAME#/$BUCKET_NAME/g" Source/postcard/appsettings.json
      - sed -i "s/#USER_ACCESS_ID#/$USER_ACCESS_ID/g" Source/postcard/appsettings.json
      - sed -i "s/#USER_ACCESS_SECRET#/$USER_ACCESS_SECRET/g" Source/postcard/appsettings.json
  build:
      commands:
        - echo Build image `date`...
        - cd Source/postcard
        - docker build -t $PROJECT_NAME:DEV .
        - docker tag $PROJECT_NAME:DEV $OWNER.dkr.ecr.$AWS_REGION.amazonaws.com/$PROJECT_NAME:DEV
  post_build:
      commands:
        - echo Pushing the Docker image `date`...
        - docker push $OWNER.dkr.ecr.$AWS_REGION.amazonaws.com/$PROJECT_NAME:DEV
        - echo Finish build `date`...
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
